version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /home/ubuntu/script/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/script/start.sh
      timeout: 60
      runas: ubuntu